# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 720)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 70, 800, 600))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(840, 70, 421, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab0 = QtWidgets.QWidget()
        self.tab0.setObjectName("tab0")
        self.grayHistoView = QtWidgets.QGraphicsView(self.tab0)
        self.grayHistoView.setGeometry(QtCore.QRect(50, 40, 320, 240))
        self.grayHistoView.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.grayHistoView.setObjectName("grayHistoView")
        self.choice11 = QtWidgets.QRadioButton(self.tab0)
        self.choice11.setGeometry(QtCore.QRect(70, 300, 111, 31))
        self.choice11.setObjectName("choice11")
        self.choiceButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.choiceButtonGroup.setObjectName("choiceButtonGroup")
        self.choiceButtonGroup.addButton(self.choice11)
        self.choice12 = QtWidgets.QRadioButton(self.tab0)
        self.choice12.setGeometry(QtCore.QRect(70, 350, 111, 31))
        self.choice12.setObjectName("choice12")
        self.choiceButtonGroup.addButton(self.choice12)
        self.para121 = QtWidgets.QDoubleSpinBox(self.tab0)
        self.para121.setGeometry(QtCore.QRect(110, 400, 62, 22))
        self.para121.setMaximum(2.0)
        self.para121.setSingleStep(0.2)
        self.para121.setProperty("value", 1.0)
        self.para121.setObjectName("para121")
        self.label_15 = QtWidgets.QLabel(self.tab0)
        self.label_15.setGeometry(QtCore.QRect(80, 400, 31, 16))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab0, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.choice21 = QtWidgets.QRadioButton(self.tab1)
        self.choice21.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.choice21.setObjectName("choice21")
        self.choiceButtonGroup.addButton(self.choice21)
        self.choice22 = QtWidgets.QRadioButton(self.tab1)
        self.choice22.setGeometry(QtCore.QRect(30, 140, 89, 16))
        self.choice22.setObjectName("choice22")
        self.choiceButtonGroup.addButton(self.choice22)
        self.choice23 = QtWidgets.QRadioButton(self.tab1)
        self.choice23.setGeometry(QtCore.QRect(30, 240, 89, 16))
        self.choice23.setObjectName("choice23")
        self.choiceButtonGroup.addButton(self.choice23)
        self.choice24 = QtWidgets.QRadioButton(self.tab1)
        self.choice24.setGeometry(QtCore.QRect(30, 300, 89, 16))
        self.choice24.setObjectName("choice24")
        self.choiceButtonGroup.addButton(self.choice24)
        self.para211 = QtWidgets.QSlider(self.tab1)
        self.para211.setGeometry(QtCore.QRect(40, 60, 341, 22))
        self.para211.setMinimum(-100)
        self.para211.setMaximum(100)
        self.para211.setSingleStep(1)
        self.para211.setSliderPosition(0)
        self.para211.setOrientation(QtCore.Qt.Horizontal)
        self.para211.setObjectName("para211")
        self.para221 = QtWidgets.QSlider(self.tab1)
        self.para221.setGeometry(QtCore.QRect(40, 160, 341, 22))
        self.para221.setMinimum(-100)
        self.para221.setMaximum(100)
        self.para221.setOrientation(QtCore.Qt.Horizontal)
        self.para221.setObjectName("para221")
        self.para222 = QtWidgets.QSlider(self.tab1)
        self.para222.setGeometry(QtCore.QRect(40, 200, 341, 22))
        self.para222.setMinimum(-100)
        self.para222.setMaximum(100)
        self.para222.setOrientation(QtCore.Qt.Horizontal)
        self.para222.setObjectName("para222")
        self.para231 = QtWidgets.QSlider(self.tab1)
        self.para231.setGeometry(QtCore.QRect(40, 270, 341, 22))
        self.para231.setMinimum(-100)
        self.para231.setMaximum(100)
        self.para231.setOrientation(QtCore.Qt.Horizontal)
        self.para231.setObjectName("para231")
        self.para212 = QtWidgets.QSlider(self.tab1)
        self.para212.setGeometry(QtCore.QRect(40, 100, 341, 22))
        self.para212.setMinimum(-100)
        self.para212.setMaximum(100)
        self.para212.setSingleStep(1)
        self.para212.setSliderPosition(0)
        self.para212.setOrientation(QtCore.Qt.Horizontal)
        self.para212.setObjectName("para212")
        self.choice25 = QtWidgets.QRadioButton(self.tab1)
        self.choice25.setGeometry(QtCore.QRect(30, 370, 89, 16))
        self.choice25.setObjectName("choice25")
        self.choiceButtonGroup.addButton(self.choice25)
        self.para241 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para241.setGeometry(QtCore.QRect(60, 330, 62, 22))
        self.para241.setMinimum(-5.0)
        self.para241.setMaximum(5.0)
        self.para241.setObjectName("para241")
        self.para242 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para242.setGeometry(QtCore.QRect(170, 330, 62, 22))
        self.para242.setMinimum(-5.0)
        self.para242.setMaximum(5.0)
        self.para242.setObjectName("para242")
        self.para253 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para253.setGeometry(QtCore.QRect(170, 400, 62, 22))
        self.para253.setMinimum(-5.0)
        self.para253.setMaximum(5.0)
        self.para253.setObjectName("para253")
        self.para251 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para251.setGeometry(QtCore.QRect(60, 400, 62, 22))
        self.para251.setMinimum(-20.0)
        self.para251.setMaximum(20.0)
        self.para251.setObjectName("para251")
        self.para255 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para255.setGeometry(QtCore.QRect(280, 400, 62, 22))
        self.para255.setMinimum(-5.0)
        self.para255.setMaximum(5.0)
        self.para255.setObjectName("para255")
        self.para252 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para252.setGeometry(QtCore.QRect(60, 440, 62, 22))
        self.para252.setMaximum(20.0)
        self.para252.setObjectName("para252")
        self.para254 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para254.setGeometry(QtCore.QRect(170, 440, 62, 22))
        self.para254.setMaximum(5.0)
        self.para254.setObjectName("para254")
        self.para256 = QtWidgets.QDoubleSpinBox(self.tab1)
        self.para256.setGeometry(QtCore.QRect(280, 440, 62, 22))
        self.para256.setMinimum(-5.0)
        self.para256.setMaximum(5.0)
        self.para256.setObjectName("para256")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(40, 400, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(40, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(150, 400, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(150, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(260, 400, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(260, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab1)
        self.label_7.setGeometry(QtCore.QRect(40, 330, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab1)
        self.label_8.setGeometry(QtCore.QRect(150, 330, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab1)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab1)
        self.label_10.setGeometry(QtCore.QRect(380, 260, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab1)
        self.label_11.setGeometry(QtCore.QRect(0, 160, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab1)
        self.label_12.setGeometry(QtCore.QRect(0, 190, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab1)
        self.label_13.setGeometry(QtCore.QRect(0, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab1)
        self.label_14.setGeometry(QtCore.QRect(0, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.choice31 = QtWidgets.QRadioButton(self.tab2)
        self.choice31.setGeometry(QtCore.QRect(40, 40, 89, 16))
        self.choice31.setObjectName("choice31")
        self.choiceButtonGroup.addButton(self.choice31)
        self.choice32 = QtWidgets.QRadioButton(self.tab2)
        self.choice32.setGeometry(QtCore.QRect(40, 130, 89, 16))
        self.choice32.setObjectName("choice32")
        self.choiceButtonGroup.addButton(self.choice32)
        self.choice33 = QtWidgets.QRadioButton(self.tab2)
        self.choice33.setGeometry(QtCore.QRect(40, 210, 89, 16))
        self.choice33.setObjectName("choice33")
        self.choiceButtonGroup.addButton(self.choice33)
        self.para311 = QtWidgets.QDoubleSpinBox(self.tab2)
        self.para311.setGeometry(QtCore.QRect(80, 70, 62, 22))
        self.para311.setMaximum(1.0)
        self.para311.setSingleStep(0.1)
        self.para311.setObjectName("para311")
        self.para321 = QtWidgets.QDoubleSpinBox(self.tab2)
        self.para321.setGeometry(QtCore.QRect(80, 160, 62, 22))
        self.para321.setMaximum(255.0)
        self.para321.setObjectName("para321")
        self.para322 = QtWidgets.QDoubleSpinBox(self.tab2)
        self.para322.setGeometry(QtCore.QRect(220, 160, 62, 22))
        self.para322.setMaximum(255.0)
        self.para322.setObjectName("para322")
        self.para331 = QtWidgets.QDoubleSpinBox(self.tab2)
        self.para331.setGeometry(QtCore.QRect(80, 240, 62, 22))
        self.para331.setMaximum(1.0)
        self.para331.setSingleStep(0.1)
        self.para331.setObjectName("para331")
        self.label_19 = QtWidgets.QLabel(self.tab2)
        self.label_19.setGeometry(QtCore.QRect(40, 70, 41, 16))
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.tab2)
        self.label_16.setGeometry(QtCore.QRect(60, 160, 21, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab2)
        self.label_17.setGeometry(QtCore.QRect(180, 160, 31, 16))
        self.label_17.setLineWidth(2)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.tab2)
        self.label_20.setGeometry(QtCore.QRect(40, 240, 41, 16))
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.choice44 = QtWidgets.QRadioButton(self.tab3)
        self.choice44.setGeometry(QtCore.QRect(40, 210, 89, 16))
        self.choice44.setObjectName("choice44")
        self.choiceButtonGroup.addButton(self.choice44)
        self.choice43 = QtWidgets.QRadioButton(self.tab3)
        self.choice43.setGeometry(QtCore.QRect(40, 140, 89, 16))
        self.choice43.setObjectName("choice43")
        self.choiceButtonGroup.addButton(self.choice43)
        self.choice41 = QtWidgets.QRadioButton(self.tab3)
        self.choice41.setGeometry(QtCore.QRect(40, 10, 89, 16))
        self.choice41.setObjectName("choice41")
        self.choiceButtonGroup.addButton(self.choice41)
        self.choice42 = QtWidgets.QRadioButton(self.tab3)
        self.choice42.setGeometry(QtCore.QRect(40, 70, 89, 16))
        self.choice42.setObjectName("choice42")
        self.choiceButtonGroup.addButton(self.choice42)
        self.choice45 = QtWidgets.QRadioButton(self.tab3)
        self.choice45.setGeometry(QtCore.QRect(40, 280, 89, 16))
        self.choice45.setObjectName("choice45")
        self.choiceButtonGroup.addButton(self.choice45)
        self.para413 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para413.setGeometry(QtCore.QRect(300, 40, 62, 22))
        self.para413.setObjectName("para413")
        self.para411 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para411.setGeometry(QtCore.QRect(60, 40, 62, 22))
        self.para411.setObjectName("para411")
        self.para412 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para412.setGeometry(QtCore.QRect(180, 40, 62, 22))
        self.para412.setObjectName("para412")
        self.para423 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para423.setGeometry(QtCore.QRect(300, 100, 62, 22))
        self.para423.setObjectName("para423")
        self.para421 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para421.setGeometry(QtCore.QRect(60, 100, 62, 22))
        self.para421.setObjectName("para421")
        self.para422 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para422.setGeometry(QtCore.QRect(180, 100, 62, 22))
        self.para422.setObjectName("para422")
        self.para433 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para433.setGeometry(QtCore.QRect(300, 170, 62, 22))
        self.para433.setObjectName("para433")
        self.para431 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para431.setGeometry(QtCore.QRect(60, 170, 62, 22))
        self.para431.setObjectName("para431")
        self.para432 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para432.setGeometry(QtCore.QRect(180, 170, 62, 22))
        self.para432.setObjectName("para432")
        self.para443 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para443.setGeometry(QtCore.QRect(300, 240, 62, 22))
        self.para443.setObjectName("para443")
        self.para441 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para441.setGeometry(QtCore.QRect(60, 240, 62, 22))
        self.para441.setObjectName("para441")
        self.para442 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para442.setGeometry(QtCore.QRect(180, 240, 62, 22))
        self.para442.setObjectName("para442")
        self.para453 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para453.setGeometry(QtCore.QRect(300, 310, 62, 22))
        self.para453.setObjectName("para453")
        self.para451 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para451.setGeometry(QtCore.QRect(60, 310, 62, 22))
        self.para451.setObjectName("para451")
        self.para452 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para452.setGeometry(QtCore.QRect(180, 310, 62, 22))
        self.para452.setObjectName("para452")
        self.para451_2 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para451_2.setGeometry(QtCore.QRect(60, 380, 62, 22))
        self.para451_2.setObjectName("para451_2")
        self.para452_2 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para452_2.setGeometry(QtCore.QRect(180, 380, 62, 22))
        self.para452_2.setObjectName("para452_2")
        self.choice46 = QtWidgets.QRadioButton(self.tab3)
        self.choice46.setGeometry(QtCore.QRect(40, 350, 89, 16))
        self.choice46.setObjectName("choice46")
        self.para453_2 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para453_2.setGeometry(QtCore.QRect(300, 380, 62, 22))
        self.para453_2.setObjectName("para453_2")
        self.choice47 = QtWidgets.QRadioButton(self.tab3)
        self.choice47.setGeometry(QtCore.QRect(40, 420, 89, 16))
        self.choice47.setObjectName("choice47")
        self.para453_3 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para453_3.setGeometry(QtCore.QRect(300, 450, 62, 22))
        self.para453_3.setObjectName("para453_3")
        self.para452_3 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para452_3.setGeometry(QtCore.QRect(180, 450, 62, 22))
        self.para452_3.setObjectName("para452_3")
        self.para451_3 = QtWidgets.QDoubleSpinBox(self.tab3)
        self.para451_3.setGeometry(QtCore.QRect(60, 450, 62, 22))
        self.para451_3.setObjectName("para451_3")
        self.tabWidget.addTab(self.tab3, "")
        self.revokeButton = QtWidgets.QPushButton(self.centralwidget)
        self.revokeButton.setGeometry(QtCore.QRect(840, 610, 201, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.revokeButton.setFont(font)
        self.revokeButton.setObjectName("revokeButton")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(1060, 610, 201, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.cmpOrigin = QtWidgets.QRadioButton(self.centralwidget)
        self.cmpOrigin.setGeometry(QtCore.QRect(710, 20, 51, 31))
        self.cmpOrigin.setObjectName("cmpOrigin")
        self.cmpbuttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.cmpbuttonGroup.setObjectName("cmpbuttonGroup")
        self.cmpbuttonGroup.addButton(self.cmpOrigin)
        self.cmpLast = QtWidgets.QRadioButton(self.centralwidget)
        self.cmpLast.setGeometry(QtCore.QRect(770, 20, 61, 31))
        self.cmpLast.setObjectName("cmpLast")
        self.cmpbuttonGroup.addButton(self.cmpLast)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(30, 20, 81, 31))
        self.openButton.setObjectName("openButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(130, 20, 81, 31))
        self.saveButton.setObjectName("saveButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(860, 580, 401, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.cmpButton = QtWidgets.QPushButton(self.centralwidget)
        self.cmpButton.setGeometry(QtCore.QRect(630, 20, 61, 31))
        self.cmpButton.setObjectName("cmpButton")
        self.exampleButton = QtWidgets.QPushButton(self.centralwidget)
        self.exampleButton.setGeometry(QtCore.QRect(1150, 20, 101, 61))
        self.exampleButton.setObjectName("exampleButton")
        self.para000 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.para000.setGeometry(QtCore.QRect(1060, 40, 62, 22))
        self.para000.setObjectName("para000")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIP GUI"))
        self.choice11.setText(_translate("MainWindow", "均衡灰度直方图"))
        self.choice12.setText(_translate("MainWindow", "灰度图增强"))
        self.label_15.setText(_translate("MainWindow", "参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("MainWindow", "灰度图"))
        self.choice21.setText(_translate("MainWindow", "放缩"))
        self.choice22.setText(_translate("MainWindow", "平移"))
        self.choice23.setText(_translate("MainWindow", "旋转"))
        self.choice24.setText(_translate("MainWindow", "错切"))
        self.choice25.setText(_translate("MainWindow", "仿射变换"))
        self.label.setText(_translate("MainWindow", "tx"))
        self.label_2.setText(_translate("MainWindow", "ty"))
        self.label_3.setText(_translate("MainWindow", "sx"))
        self.label_4.setText(_translate("MainWindow", "sy"))
        self.label_5.setText(_translate("MainWindow", "mx"))
        self.label_6.setText(_translate("MainWindow", "my"))
        self.label_7.setText(_translate("MainWindow", "mx"))
        self.label_8.setText(_translate("MainWindow", "my"))
        self.label_9.setText(_translate("MainWindow", "-360°"))
        self.label_10.setText(_translate("MainWindow", "+360°"))
        self.label_11.setText(_translate("MainWindow", "水平"))
        self.label_12.setText(_translate("MainWindow", "竖直"))
        self.label_13.setText(_translate("MainWindow", "水平"))
        self.label_14.setText(_translate("MainWindow", "竖直"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "几何变换"))
        self.choice31.setText(_translate("MainWindow", "椒盐噪声"))
        self.choice32.setText(_translate("MainWindow", "高斯噪声"))
        self.choice33.setText(_translate("MainWindow", "随机噪声"))
        self.label_19.setText(_translate("MainWindow", "信噪比"))
        self.label_16.setText(_translate("MainWindow", "μ"))
        self.label_17.setText(_translate("MainWindow", "sigma"))
        self.label_20.setText(_translate("MainWindow", "信噪比"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "添加噪声"))
        self.choice44.setText(_translate("MainWindow", "RadioButton"))
        self.choice43.setText(_translate("MainWindow", "RadioButton"))
        self.choice41.setText(_translate("MainWindow", "平滑"))
        self.choice42.setText(_translate("MainWindow", "RadioButton"))
        self.choice45.setText(_translate("MainWindow", "RadioButton"))
        self.choice46.setText(_translate("MainWindow", "RadioButton"))
        self.choice47.setText(_translate("MainWindow", "RadioButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "滤波变换"))
        self.revokeButton.setText(_translate("MainWindow", "撤销"))
        self.updateButton.setText(_translate("MainWindow", "应用并预览"))
        self.cmpOrigin.setText(_translate("MainWindow", "原图"))
        self.cmpLast.setText(_translate("MainWindow", "上一步"))
        self.openButton.setText(_translate("MainWindow", "打开文件"))
        self.saveButton.setText(_translate("MainWindow", "保存文件"))
        self.cmpButton.setText(_translate("MainWindow", "对比"))
        self.exampleButton.setText(_translate("MainWindow", "样例按钮"))

